// const express = require('express'); 
// const router = express.Router();    
// const axios = require('axios'); 

// const Assessment = require('../models/Assessment');
// const verifyToken = require('../middleware/authMiddleware');

// // server/routes/assessmentRoutes.js

// // server/routes/assessmentRoutes.js

// // server/routes/assessmentRoutes.js

// // server/routes/assessmentRoutes.js

// router.post('/save', verifyToken, async (req, res) => {
//   try {
//     const { responses, formattedQuestions } = req.body;

//     if (!responses) {
//       return res.status(400).json({ error: "No answers found in request body." });
//     }

//     const apiKey = process.env.OPENAI_API_KEY; // This now securely holds your Gemini key from Render
//     if (!apiKey) {
//       return res.status(500).json({ error: "Backend environment key configuration is missing." });
//     }

//     // Prepare the text data layout for Gemini to read
//     const aiPromptInput = formattedQuestions 
//       ? JSON.stringify(formattedQuestions) 
//       : JSON.stringify(responses);

//     // Call Google Gemini 1.5 Flash (100% Free Tier)
//     const geminiResponse = await axios.post(
//       `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
//       {
//         contents: [{
//           parts: [{
//             text: `You are a professional career guidance engine. Analyze these user answers carefully and output ONLY a valid JSON object matching this exact format: {"recommended_field": "string", "confidence": "Low"|"Medium"|"High", "reasoning": "string", "suggested_skills": ["string"]}. Do not include markdown wraps or backticks like \`\`\`json. Return pure raw JSON string text only. User responses: ${aiPromptInput}`
//           }]
//         }],
//         generationConfig: {
//           responseMimeType: "application/json" // Strict JSON output validation configuration
//         }
//       },
//       { headers: { 'Content-Type': 'application/json' } }
//     );

//     // Extract the content string out of Google's response object layout structure
//     const rawContent = geminiResponse.data.candidates[0].content.parts[0].text;
//     const aiResult = JSON.parse(rawContent);

//     // Map confidence string to a numeric value for database schema storage consistency
//     const confidenceScoreMap = { "High": 92, "Medium": 74, "Low": 48 };
//     const mappedScore = confidenceScoreMap[aiResult.confidence] || 80;

//     // Build the dynamic data payload to store inside your MongoDB Cluster collection
//     const newAssessment = new Assessment({
//       userId: req.user.id, 
//       responses: responses,
//       recommendation: {
//         primaryField: aiResult.recommended_field || "General Field",
//         confidenceScore: mappedScore,
//         analysisDate: new Date(),
//         reasoning: aiResult.reasoning || "Analysis successfully generated by system core engine."
//       },
//       suggested_skills: aiResult.suggested_skills || []
//     });

//     const savedAssessment = await newAssessment.save();
//     res.status(201).json(savedAssessment);

//   } catch (err) {
//     console.error("Gemini API processing or DB save failure:", err.message);
//     res.status(400).json({ 
//       error: "Failed to process profile evaluation structure gracefully.",
//       details: err.message 
//     });
//   }
// });
// // 2. GET USER'S HISTORY (Protected Route)
// router.get('/history', verifyToken, async (req, res) => {
//   try {
//     const history = await Assessment.find({ userId: req.user.id }).sort({ createdAt: -1 });
//     res.json(history);
//   } catch (err) {
//     res.status(500).json({ error: "Failed to fetch history" });
//   }
// });

// // 3. DELETE SINGLE RECORD ENTRY (Protected Route)
// router.delete('/delete/:id', verifyToken, async (req, res) => {
//   try {
//     const assessment = await Assessment.findOne({ _id: req.params.id, userId: req.user.id });
    
//     if (!assessment) {
//       return res.status(404).json({ error: "Assessment record not found or unauthorized" });
//     }

//     await Assessment.findByIdAndDelete(req.params.id);
//     res.json({ message: "Assessment record deleted successfully" });
//   } catch (err) {
//     res.status(500).json({ error: "Failed to delete assessment record" });
//   }
// });

// module.exports = router;

const express = require('express'); 
const router = express.Router();    
const axios = require('axios'); 

const Assessment = require('../models/Assessment');
const verifyToken = require('../middleware/authMiddleware');

// 1. SAVE NEW ASSESSMENT (Protected Route)
router.post('/save', verifyToken, async (req, res) => {
  try {
    const { responses, formattedQuestions } = req.body;

    if (!responses) {
      return res.status(400).json({ error: "No answers found in request body." });
    }

    const apiKey = process.env.OPENAI_API_KEY; 
    if (!apiKey) {
      return res.status(500).json({ error: "Backend environment key configuration is missing." });
    }

    const aiPromptInput = formattedQuestions 
      ? JSON.stringify(formattedQuestions) 
      : JSON.stringify(responses);

    // ✅ FIXED ENDPOINT: Targeting the active, free gemini-2.5-flash model via stable v1 path
    const geminiResponse = await axios.post(
      `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        contents: [{
          parts: [{
            text: `You are an expert career advisor. Evaluate these questionnaire user results and return a raw JSON string. The response MUST perfectly parse into this JSON schema: {"recommended_field": "string", "confidence": "Low"|"Medium"|"High", "reasoning": "string", "suggested_skills": ["string"]}. Do not wrap the code block inside backticks, markdown, or text formatting. Just output the clean raw JSON data payload directly. Question metrics: ${aiPromptInput}`
          }]
        }]
      },
      { headers: { 'Content-Type': 'application/json' } }
    );

    if (!geminiResponse.data || !geminiResponse.data.candidates) {
      throw new Error("Invalid payload signature returned from upstream Gemini API.");
    }

    const rawContent = geminiResponse.data.candidates[0].content.parts[0].text.trim();
    
    // Safety check to clean away rogue markdown markup strings if the model slips up
    const cleanJsonString = rawContent.replace(/```json|```/g, "").trim();
    const aiResult = JSON.parse(cleanJsonString);

    const confidenceScoreMap = { "High": 92, "Medium": 74, "Low": 48 };
    const mappedScore = confidenceScoreMap[aiResult.confidence] || 80;

    const newAssessment = new Assessment({
      userId: req.user.id, 
      responses: responses,
      recommendation: {
        primaryField: aiResult.recommended_field || "General Technology",
        confidenceScore: mappedScore,
        analysisDate: new Date(),
        reasoning: aiResult.reasoning || "Evaluation processed successfully via cloud metrics validation."
      },
      suggested_skills: aiResult.suggested_skills || []
    });

    const savedAssessment = await newAssessment.save();
    res.status(201).json(savedAssessment);

  } catch (err) {
    console.error("Critical Route Exception:", err.message);
    res.status(400).json({ 
      error: "Failed to process profile evaluation structure gracefully.",
      details: err.message 
    });
  }
});

// 2. GET USER'S HISTORY (Protected Route)
router.get('/history', verifyToken, async (req, res) => {
  try {
    const history = await Assessment.find({ userId: req.user.id }).sort({ createdAt: -1 });
    res.json(history);
  } catch (err) {
    res.status(500).json({ error: "Failed to fetch history" });
  }
});

// 3. DELETE SINGLE RECORD ENTRY (Protected Route)
router.delete('/delete/:id', verifyToken, async (req, res) => {
  try {
    const assessment = await Assessment.findOne({ _id: req.params.id, userId: req.user.id });
    
    if (!assessment) {
      return res.status(404).json({ error: "Assessment record not found or unauthorized" });
    }

    await Assessment.findByIdAndDelete(req.params.id);
    res.json({ message: "Assessment record deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: "Failed to delete assessment record" });
  }
});

module.exports = router;